//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employee
    {
        public int Id { get; set; }
        [DisplayName("Employee Name")]
        public string employeeName { get; set; }
        [DisplayName("Employee No")]
        public string employeeNo { get; set; }
        [DisplayName("Department Name")]
        public Nullable<int> departmentId { get; set; }
        [DisplayName("Salay")]
        public string salary { get; set; }
        [DisplayName("Joining Date")]
        public string joiningDate { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
